// source/stencil/src/components/hue-slider-stencil/hue-slider-stencil.tsx
import { Component, Prop, State, Event, EventEmitter, Watch } from '@stencil/core';

@Component({
  tag: 'hue-slider-stencil',
  styleUrl: 'hue-slider-stencil.css',
  shadow: true
})

export class HueSlider {
  @Prop({reflectToAttr: true, mutable: true}) hue: string = '100';

  @State() inputValue: string;
  @State() value: string;

  @Event({eventName: 'input'}) inputEvent: EventEmitter;

  handleInput(e) {
    e.stopPropagation()
    const { value } = e.target
    this.hue = value
    this.inputValue = value
    this.inputEvent.emit({ value })
  }

  componentWillLoad() {
    this.value = this.hue
  }

  @Watch('hue')
  hueUpdated(newValue) {
    this.value = newValue
  }

  render() {
    return (
      <label class="hue-slider">
        <input type="range" min="0" max="360" value={`${this.hue}`} onInput={(e) => this.handleInput(e)} />
        <output style={{ backgroundColor: this.value }}>
          <slot></slot>
        </output>
      </label>
    );
  }
}

// source/vue/src/components/HueSlider.vue
<template>
  <label class="hue-slider">
    <input type="range" min="0" max="360" :value="inputValue" @input.stop="onInput" @change.stop="onChange">
    <output :style="`background-color: hsl(${inputValue}, 100%, 50%)`">
      <slot />
    </output>
  </label>
</template>

<script>
  export default {
    name: 'HueSlider',
    props: ['hue'],
    data: () => ({
      inputValue: null,
      value: 0
    }),
    methods: {
      setValue(val) {
        this.value = val
      },
      onInput(e) {
        this.inputValue = e.target.value
        this.setValue(this.inputValue)
        this.$emit('input')
      },
      onChange(e) {
        this.inputValue = e.target.value
        this.setValue(this.inputValue)
        this.$emit('change')
      }
    },
    mounted() {
      this.inputValue = this.hue
        ? this.hue
        : this.$el.querySelector('input').value

      this.setValue(this.inputValue)
    },
    watch: {
      hue(newValue) {
        this.inputValue = newValue
      }
    }
  }
</script>

<style>
  .hue-slider {
    display: flex;
  }

  .hue-slider output {
    display: inline-block;
    width: 50px;
    height: 50px;
    margin-left: 10px;
  }
</style>
