// source/stencil/src/components/hue-slider-stencil/hue-slider-stencil.tsx
import { Component, Prop, State, Event, EventEmitter, Watch } from '@stencil/core';

@Component({
  tag: 'hue-slider-stencil',
  styleUrl: 'hue-slider-stencil.css',
  shadow: true
})

export class HueSlider {
  @Prop({reflectToAttr: true, mutable: true}) hue: string = '100';

  @State() inputValue: string;
  @State() value: string;

  @Event({eventName: 'input'}) inputEvent: EventEmitter;

  handleInput(e) {
    e.stopPropagation()
    const { value } = e.target
    this.hue = value
    this.inputValue = value
    this.inputEvent.emit({ value })
  }

  componentWillLoad() {
    this.value = this.hue
  }

  @Watch('hue')
  hueUpdated(newValue) {
    this.value = newValue
  }

  render() {
    return (
      <label class="hue-slider">
        <input type="range" min="0" max="360" value={`${this.hue}`} onInput={(e) => this.handleInput(e)} />
        <output style={{ backgroundColor: this.value }}>
          <slot></slot>
        </output>
      </label>
    );
  }
}

// source/react/src/component/hue-slider.js
import React from 'react';
import ReactWebComponent from 'react-web-component';
import PropTypes from 'prop-types';

import './hue-slider.css';

export default class HueSlider extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      hue: props.hue || '0',
    };
  }

  handleChange = (e) => {
    const { value } = e.target;

    this.setState({ hue: value });
  }

  /**
    * props is updated parsed by react-web-component just before invoking this
    * method but react doesn't detect this change to props so copy it to
    * state and use state instead.
    */
  webComponentConstructed() {
    this.setState(this.props);
  }

  render() {
    const { hue } = this.state;
    const { children } = this.props;

    return (
      <label className="hue-slider">
        <input type="range" min="0" max="360" value={hue} onChange={this.handleChange} />
        <output style={{ backgroundColor: `hsl(${hue}, 100%, 50%)` }}>
          { children }
        </output>
      </label>
    );
  }
}

HueSlider.propTypes = {
  hue: PropTypes.string,
  children: PropTypes.node,
};

ReactWebComponent.create(<HueSlider />, 'hue-slider-react');
