// source/vue/src/App.vue
<template>
  <div class="app">
    <color-picker-vue />
    <color-picker-vue :hue="100"/>
    <color-picker-vue>
      <input type="number" max="360">
    </color-picker-vue>
  </div>
</template>

<script>
import ColorPickerVue from "./components/ColorPickerVue";
export default {
  components: {
    ColorPickerVue
  }
}
</script>

<style>
.app {
  display: flex;
  flex-direction: column;
}

.app > * {
  margin-bottom: 1rem
}
</style>

// source/react/src/app.js
import React from 'react';
import ColorPicker from './color-picker';

const App = () => (
  <div>
    <h2>React components</h2>
    <ColorPicker />
    <ColorPicker hue={180} />
    <ColorPicker>
      <input type="number" min="0" max="360" step="1" />
    </ColorPicker>
  </div>
);

export default App;
